### ISSUE TITLE
我装了xc11，启动的第一个sample时候预览不了，报Keyword '_' cannot be used as an identifier here

### ISSUE THREAD

**Issue by zacard-orc** [WillieWangWei/SwiftUI-Tutorials#1]
我装了xc11，启动的第一个sample时候预览不了，报Keyword '_' cannot be used as an identifier here。发现是在_xctest.swift这个文件里有报错，

import XCTest
@testable import _

class _Tests: XCTestCase {

请问如何解决啊

**Comment by WillieWangWei** [comment]
1. 确保你的 macOS 是最新的 beta 版本。
2. 尝试新建一个新的 SwiftUI 空项目，看是否能 Run。
3. 如果新项目也不能 Run，说明是 SwiftUI 自身的 bug，目前 bug 还相当多。如果新项目能 Run 而此仓库代码不行，可以在教程页下载官方的初始代码再次尝试。
