### ISSUE TITLE
I can't build successfully, too many errors.

### ISSUE THREAD

**Issue by sail-cn** [WillieWangWei/SwiftUI-Tutorials#2]
After I downloaded from github, I want to run it. But there are too many swift compiler errors. "Missing flies", or "Unable to infer complex closure return type; add explicit type to disambiguate"  etc.

**Comment by WillieWangWei** [comment]
I have no problem here. Can you try to list some specific error messages or screenshots?

**Comment by sail-cn** [comment]
![image](https://user-images.githubusercontent.com/8113409/61940780-b9fa0100-afc8-11e9-98c2-b6e5b311cb9b.png)

**Comment by WillieWangWei** [comment]
1. Make sure you are using macOS 10.15 Beta and Xcode 11 beta.
2. Create a new SwiftUI project and build it.
3. Build with the official sample code: https://developer.apple.com/tutorials/swiftui/creating-and-combining-views
