### ISSUE TITLE
Building Lists and Navigation 中 MapView 无法传递 coordinate

### ISSUE THREAD

**Issue by YuiGuizhichen** [WillieWangWei/SwiftUI-Tutorials#7]
您好
`let coordinate = CLLocationCoordinate2D(latitude: 29.554987, longitude: 115.984963)`
在注释掉上行代码后添加 
`var coordinate: CLLocationCoordinate2D`

并在 PreviewProvider 中给 MapView() 添加
 `MapView(coordinate: landmarkData[0].locationCoordinate)`

预览视图就报错了，求解，感谢🙏

代码 
<img width="662" alt="image" src="https://user-images.githubusercontent.com/49800659/86997313-58827080-c1e0-11ea-94dd-9f1e83ab69e4.png">
错误信息
<img width="559" alt="image" src="https://user-images.githubusercontent.com/49800659/86997397-8798e200-c1e0-11ea-8e78-082d6bb62184.png">

**Comment by WillieWangWei** [comment]
查看你的 `landmarkData` 数据是否正确，以及项目 `Resources` 目录下的文件是否和示例一致。

**Comment by YuiGuizhichen** [comment]
感谢，我数据中经纬度写反了。。错误太低级了 😂
